/**
 * Mini xRM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ActivitySortFieldView = {
    Subject: 'subject',
    Type: 'type',
    DurationMinutes: 'durationMinutes',
    PersonResponsible: 'personResponsible',
    PartnerName: 'partner.name'
} as const;
export type ActivitySortFieldView = typeof ActivitySortFieldView[keyof typeof ActivitySortFieldView];

