/**
 * Mini xRM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartnerView } from './partnerView';


export interface PartnerPageView { 
    totalElements: number;
    totalPages: number;
    /**
     * The current page number (0-based)
     */
    currentPage: number;
    pageSize: number;
    content: Array<PartnerView>;
}

