/**
 * Mini xRM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PartnerVSortFieldView = {
    Name: 'name',
    TaxNumber: 'taxNumber',
    Headquarters: 'headquarters',
    Status: 'status'
} as const;
export type PartnerVSortFieldView = typeof PartnerVSortFieldView[keyof typeof PartnerVSortFieldView];

