/**
 * Mini xRM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PartnerStatusView = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type PartnerStatusView = typeof PartnerStatusView[keyof typeof PartnerStatusView];

