/**
 * Mini xRM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartnerTagView } from './partnerTagView';


export interface PartnerVView { 
    id: number;
    name: string;
    taxNumber: string;
    headquarters: string;
    status: string;
    tags: Array<PartnerTagView>;
}

