/**
 * Mini xRM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartnerStatusView } from './partnerStatusView';
import { PartnerTagView } from './partnerTagView';


export interface PartnerView { 
    id: number;
    name: string;
    taxNumber: string;
    headquarters: string;
    status: PartnerStatusView;
    tags: Array<PartnerTagView>;
}
export namespace PartnerView {
}


