resilience4j:
  retry:
    instances:
      optimisticLockingRetry:
        max-attempts: 3
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.dao.OptimisticLockingFailureException
