spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miniXrm
    username: miniXrm
    password: miniXrm
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
    url: /openapi-v1.yaml